new: финальный проект 13 спринта
Aloizzza/java-shareit pull request #1
Opened 2022-10-22 19:45 UTC by Aloizzza

2022-10-23 05:57 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-10-23 05:57 UTC, FanaticFiz commented on README.md
> +
`pom` файл не менялся.
Напишу коммент в произвольном месте...

1. Хорошей практикой будет указать кодировку
`<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

2. Советую всем соблюдать некий порядок при объявлении зависимостей.
Сначала "главный" `spring` все его зависимости и всё о нём.
Потом по степени "тяжеловестности" остальные зависимости. Ну и у меня в проекте, например, последними идёт еще одна секция наши собственные библиотеки/модули/контракты.

2022-10-23 05:57 UTC, FanaticFiz commented on README.md
> +Наше приложение **умеет**:
И я снова комментирую файл настроек `application.properties`, так как он не менялся, тоже тут напишу...

Я буду топить за то чтобы вы привыкали к написанию файла свойств для приложения в формате `yaml -> application.yml`
Мне трудно сейчас представить проект в котором до сих пор на него не пересели!

2022-10-23 05:57 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        return new ErrorResponse(e.getMessage());
Желательно логировать приизошедшее событие...
Желательно со стектрейсом.

2022-10-23 05:57 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ValidationException.java
> +    public ValidationException(String message) {
Да этот ексепшн мы выстреливаем при валидации, но у нас веб сервис и для нас это плохой запрос. 
Поэтому `BadRequestException` лучше.

2022-10-23 05:57 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemStorage.java
> +    public Optional<Item> getById(long id) {
Давай в хранилищах использовать глагол `find`.
И правильно и хорошо что использовала `Optional`. 
Теперь пойдем в сервис и напишем там код исходя из Optional

2022-10-23 05:57 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final InMemoryItemStorage inMemoryItem;
Хранилища же тоже могут имплементить интерфейс. 
Тогда даже при замене конкретных реализаций (переходе на БД например) тебе не придётся менять код по всему приложению.

2022-10-23 05:57 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Optional<Item> item = inMemoryItem.getById(itemId);
Воспользуйся `orElseThrow` и получи чистый Item

2022-10-23 05:57 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserStorage.java
> +        if (!users.containsKey(id)) {
Ну постой, почему же?
Почему в `ItemStorage` метод `getById` был написан по одному, а тут по другому?
Там было правильно... хранилище не решает кидать ексепшн или нет, это будет делать сервис.
Просто отдаём пользователя как `Optional<User>`

2022-10-23 05:57 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserStorage.java
> +                throw new AlreadyExistsException("почта " + email + " уже занята другим пользователем");
Логика приложения в сервисе!

2022-10-23 05:57 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (inMemoryItem.getById(itemId).get().getOwner().getId() != userId) {
Ты делаешь `inMemoryItem.getById(itemId)` дважды! Зачем?

Последовательность при обновлении:
- пошли в репозиторий спросили сущность `Item` (если её нет сразу упали)
- полученную сущность обновили полями из dto (это тот код который сейчас у тебя написан в хранилище!)

```
		if (itemDto.getName() != null) {
			item.setName(itemDto.getName());
		}
```

- обновлённую сущность `Item` сохранили в репозиторий `inMemoryItem.update(item)`
- вернули обновлённую сущность смапленную в dto ItemMapper.toItemDto(item)

2022-10-23 05:57 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return inMemoryUser.getAll().stream().map(UserMapper::toUserDto).collect(Collectors.toList());
Даже если вся цепочка влазит в строку до 120 символов лучше будет переносить на новую строку отдельные операции.

```
    public List<UserDto> getAll() {
        return inMemoryUser.getAll().stream()
                           .map(UserMapper::toUserDto)
                           .collect(Collectors.toList());
    }
```

2022-10-24 18:21 UTC, Aloizzza commented on README.md
> +
Поправила. А к чему вообще относится эта кодировка? К содержащемуся в String? К содержимому базы данных? Или к тому на какой кодировке будет вывод в консоли, на странице браузера? Этот момент совершенно не понимаю(

2022-10-24 18:51 UTC, Aloizzza commented on README.md
> +Наше приложение **умеет**:
Об этом не было ничего в теории, можешь внести рацпредложение ;) пишут yaml более удобочитаемый. А какие еще видишь преимущества?

2022-10-24 19:41 UTC, Aloizzza commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        return new ErrorResponse(e.getMessage());
Кстати, оно у меня в итоге не используется(

2022-10-24 20:48 UTC, Aloizzza commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserStorage.java
> +        if (!users.containsKey(id)) {
Исправила, у меня тут упорно появлялся NullPointer и это самое топорное решение из всех что мне пришли в голову)) Теперь с твоим .orElseThrow всё нормально работает

2022-10-24 21:22 UTC, Aloizzza commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserStorage.java
> +                throw new AlreadyExistsException("почта " + email + " уже занята другим пользователем");
Перенесла в сервис, но мне кажется неправильно это делать через вызов findAll, можно как-то изящнее? Думала аннотации в User могут, но не нашла как

2022-10-25 18:27 UTC, FanaticFiz commented on README.md
> +
Давай я тебя просто направлю сюда
https://www.baeldung.com/maven-encoding

2022-10-25 18:32 UTC, FanaticFiz commented on README.md
> +Наше приложение **умеет**:
Да, мы регулярно отправляем что то на улучшение...
YAML
- понятен человеку
- выразителен
- лёгкий в реализации и использовании

2022-10-25 18:36 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserStorage.java
> +                throw new AlreadyExistsException("почта " + email + " уже занята другим пользователем");
Да, когда будет реализация на БД, построишь запрос...

2022-10-25 18:47 UTC, FanaticFiz approved these changes

2022-10-25 18:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        return new ErrorResponse(e.getMessage());
Это потому что приложение нормально работает...
пока что )))

2022-10-25 18:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return ItemMapper.toItemDto(inMemoryItem.findById(itemId)
Не прячь такие важные вызовы методов, вот так лучше/нагляднее

```
    public ItemDto getById(long itemId) {
        Item item = inMemoryItem.findById(itemId)
                                .orElseThrow(() -> new NotFoundException("вещь c id: " + itemId + " не существует"));
        
        return ItemMapper.toItemDto(item);
    }
```

2022-10-25 18:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return inMemoryItem.findAll()
Перед `return`, делай отступ в одну строку.
Улучшит читаемость.

Исключением будет только если метод сразу начинается с `return`, как например у тебя в search методе

2022-10-25 18:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserStorage.java
> +                throw new AlreadyExistsException("почта " + email + " уже занята другим пользователем");
Это тоже логика которая должна была бы переехать в сервис.

2022-10-27 09:08 UTC, merged