new: финальный проект 14 спринта
Aloizzza/java-shareit pull request #2
Opened 2022-11-12 23:20 UTC by Aloizzza

2022-11-13 12:05 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-13 12:05 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
Не хватает выравнивания

```
CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user_id PRIMARY KEY (id),
    CONSTRAINT uq_email UNIQUE (email)
);
```

2022-11-13 12:05 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +    email VARCHAR(512) NOT NULL,
Не забыла про NOT NULL - хорошо!

2022-11-13 12:05 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @Column(nullable = false)
nullable = false, опять таки не забыла!
Но, нужно еще указать длину поля как в БД.

2022-11-13 12:05 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new BadRequest("время бронирования указано не корректно");
BadRequest -> BadRequestException назови все классы эксепшенов одинаково

2022-11-13 12:05 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        booking.setStatus(status ? BookingStatus.APPROVED : BookingStatus.REJECTED);
Отлично! Тернарник пришелся кстати!

Заимпорти статики, тогда будет читабельнее

`booking.setStatus(status ? APPROVED : REJECTED);`

2022-11-13 12:05 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return BookingMapper.toBookingDto(bookingRepository.save(booking));
Мне не нравится когда основное действие прячут...
Главное что происходит в этом методе это сохранение, оно достойно отдельной строки кода.

2022-11-13 12:05 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return findBookings(bookingRepository.findAllByBookerIdOrderByStartDesc(bookerId), state).stream()
Не хватает пустой строки перед return.

Я писал тебе уже о том что желательно его отделять?

2022-11-13 12:05 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public List<Booking> findBookings(List<Booking> bookings, String state) {
Получается что мы фильтруем по данным которые только что достали из БД.
Почему бы не построить запросы в БД так чтобы они отдавали сразу то что нужно?

2022-11-13 12:05 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    List<Item> findAllByNameContainsIgnoreCaseOrDescriptionContainsIgnoreCaseAndAvailableIsTrue(String text1, String text2);
Пожалуй лучше смотрится запрос

```
    @Query(" select i from Item i " +
            "where i.available = true and" +
            " (upper(i.name) like upper(concat('%', ?1, '%')) " +
            "  or upper(i.description) like upper(concat('%', ?1, '%')))")
    List<Item> search(String text);
```

Репозиторий который можно собрать из ключевых слов хорош чтобы набросать по быстрому...
Но бывает слишком громоздок, как тут и получилось...

2022-11-13 12:05 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        System.out.println("bookingsCount=" + bookingsCount);
Нуууу какой же `System.out.println` - ЛОГГЕР !!
Используй логгер!

2022-11-13 14:16 UTC, Aloizzza commented on src/main/resources/schema.sql
> +    email VARCHAR(512) NOT NULL,
Это было в примере в ТЗ :-) но я распространила на все таблицы

2022-11-13 14:18 UTC, Aloizzza commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @Column(nullable = false)
Я правда не совсем поняла для чего оно

2022-11-13 14:20 UTC, Aloizzza commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @Column(nullable = false)
Получается, и модель валидирует и БД

2022-11-13 14:38 UTC, Aloizzza commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return findBookings(bookingRepository.findAllByBookerIdOrderByStartDesc(bookerId), state).stream()
Да, и не раз. И я помню, но иногда забываю проверить

2022-11-13 17:27 UTC, Aloizzza commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    List<Item> findAllByNameContainsIgnoreCaseOrDescriptionContainsIgnoreCaseAndAvailableIsTrue(String text1, String text2);
Ну вот, я так старалась)))

2022-11-13 17:41 UTC, Aloizzza commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        System.out.println("bookingsCount=" + bookingsCount);
ааааа, сорри)) у меня какая-то странная ошибка лезла про Cast и Long, я никак не могла понять в чем причина. Думала в консоль выведется значение, но фиг)

2022-11-13 17:46 UTC, Aloizzza commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        System.out.println("bookingsCount=" + bookingsCount);
Что-то я про логгер забыла...ща буду его везде пихать(((

2022-11-14 02:01 UTC, FanaticFiz approved these changes

2022-11-19 18:47 UTC, merged