new: финальный проект 15 спринта
Aloizzza/java-shareit pull request #3
Opened 2022-11-30 15:17 UTC by Aloizzza

2022-12-04 08:04 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-04 08:04 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (from < 0 || size < 0) {
Смотри, этот кусочек с проверкой `from` and `size` дублируется. Но и проверка входных параметров это зона ответственности контроллера.
В идеале еще там это надо было проверить, и сформировать из них `PageRequest` сразу... и передавать уже его.

2022-12-04 08:04 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +
У тебя 4-е! раза дублируются строки кода, надо с этим что-то сделать!

![image](https://user-images.githubusercontent.com/3994663/205480128-15e1be40-b870-4129-8ecb-1e4da629065e.png)

2022-12-04 08:04 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    .orElse(null);
лучше, пожалуй, orElseThrow и в ексепшене сказать чего не хватает.
Если это конечно не нарушит логику работы.

2022-12-04 08:04 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +                                itemRepository.findItemsByRequestId(itemRequestDtoOutput.getId())
Плохо в цикле выполнял заходы в БД за новыми сущностями! 
Получается N+1 запрос... когда мы для одной сущности делаем еще N запросов за связанными объектами.

Надо вытаскивать связанные сущности одним запросом.

2022-12-04 08:04 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        Request request = requestRepository.findById(requestId)
А вот тут же тоже можно собрать все действия в цепочку, как ты делала это выше... и тут для одного объекта это будет допустимо и уместно.

2022-12-04 08:04 UTC, FanaticFiz commented on src/test/java/ru/practicum/shareit/request/RequestControllerTest.java
> +        UserDto user = userController.save(userDto);
Помнишь про `Arrange` `Act` `Assert` ??

Тесты всегда делятся на три фазы: подготовка данных, действие и проверка результатов.

Так вот, если тест не получается уместить в несколько строк, то уместно отделить эти фазы друг от друга виртуально — пустыми строками.

А если тест получается совсем громоздким (чего конечно следует избегать) то уместно и указать фазы явно

2022-12-04 12:23 UTC, Aloizzza commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (from < 0 || size < 0) {
А ведь еще и как компактнее...

2022-12-04 13:23 UTC, Aloizzza commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +
сделала отдельный метод, но всё равно эта конструкция кажется мне нелепой(

2022-12-04 13:32 UTC, Aloizzza commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    .orElse(null);
Тогда падают тесты( Эта требуха для перевода сущности в сущность Dto и обратно, тут если не было бронирований надо всё равно что-то указать, вот null запихнула. Мне самой не нравится, но нет идеи как от этого избавиться

2022-12-04 22:22 UTC, Aloizzza commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        Request request = requestRepository.findById(requestId)
Тут не поняла что нужно сделать. В одно действие записать не получается

2022-12-05 05:43 UTC, FanaticFiz approved these changes

2022-12-05 05:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    @Query(" select i from Item i " +
Оформляй SQL запросы. Пиши спец. слова в верхнем регистре: `CREATE`, `FROM`, `AND`

2022-12-05 08:18 UTC, merged