new: финальный проект 16 спринта
Aloizzza/java-shareit pull request #4
Opened 2022-12-11 16:04 UTC by Aloizzza

2022-12-12 19:36 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-12 19:36 UTC, FanaticFiz commented on gateway/src/main/java/ru/practicum/shareit/ShareItGateway.java
> +    public static void main(String[] args) {
Очень люблю этот класс, в нём никто не делает ошибок! )))

2022-12-12 19:36 UTC, FanaticFiz commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
Валидация только в одном сервисе!
Соответственно и зависимость тут не нужна.

2022-12-12 19:36 UTC, FanaticFiz commented on server/src/main/resources/application.properties
> +server.port=9090
ну а эти свойства почему же не в YAML формате!?

2022-12-13 11:20 UTC, Aloizzza commented on gateway/src/main/java/ru/practicum/shareit/ShareItGateway.java
> +    public static void main(String[] args) {
Это потому что он из исходных данных! https://github.com/yandex-praktikum/java-shareit/blob/add-docker/gateway/src/main/java/ru/practicum/shareit/ShareItGateway.java

2022-12-13 11:26 UTC, Aloizzza commented on server/src/main/resources/application.properties
> +server.port=9090
Я установила какой-то плагин, который properties превращает в yaml и он почему-то часть строк не конвертирует

2022-12-13 11:26 UTC, Aloizzza commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
точно...

2022-12-13 14:21 UTC, Aloizzza commented
Совершенно не работает с application.yml, не понимаю почему

2022-12-13 14:27 UTC, FanaticFiz commented
> Совершенно не работает с application.yml, не понимаю почему

Опустим, это не обязательное...

2022-12-13 14:28 UTC, Aloizzza commented
Я б хотела понять(

2022-12-13 20:18 UTC, FanaticFiz approved these changes

2022-12-14 15:57 UTC, merged